[programs.localnet]
charm = "BFXsCPze92SjvpLfh2axdkR4qUzjrambaDtodEJG7qa9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
